"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import styles from "./admin.module.css";

type Role="admin"|"manager"|"viewer"; type User={id:number;name:string;email:string;role:Role;active?:boolean};
type Reservation={id:number;name:string;phone:string;email:string;service:string;address:string;note:string;status:"active"|"completed"};
type Package={id:number;name:string;price:string;showCurrency:boolean;items:string[]};
type View="active"|"completed"|"pricing"|"users";

export default function AdminPage(){
 const [user,setUser]=useState<User|null>(null),[bootstrap,setBootstrap]=useState(false),[authLoading,setAuthLoading]=useState(true),[error,setError]=useState("");
 const [reservations,setReservations]=useState<Reservation[]>([]),[packages,setPackages]=useState<Package[]>([]),[users,setUsers]=useState<User[]>([]),[view,setView]=useState<View>("active");
 const [pendingDelete,setPendingDelete]=useState<Reservation|null>(null),[busy,setBusy]=useState<number|string|null>(null),[message,setMessage]=useState("");

 async function loadData(current:User){
  const calls=[fetch("/api/v2/reservations",{cache:"no-store"}),fetch("/api/v2/pricing",{cache:"no-store"})];
  if(current.role==="admin") calls.push(fetch("/api/v2/users",{cache:"no-store"}));
  const responses=await Promise.all(calls); if(responses.some(r=>!r.ok)) throw new Error("Data administrace se nepodařilo načíst.");
  setReservations(((await responses[0].json()) as {reservations:Reservation[]}).reservations);
  setPackages(((await responses[1].json()) as {packages:Package[]}).packages);
  if(responses[2]) setUsers(((await responses[2].json()) as {users:User[]}).users);
 }
 useEffect(()=>{Promise.all([fetch("/api/v2/auth/me"),fetch("/api/v2/auth/bootstrap")]).then(async([me,b])=>{setBootstrap(((await b.json()) as {available:boolean}).available);if(me.ok){const u=((await me.json()) as {user:User}).user;setUser(u);await loadData(u)}}).catch(()=>setError("Databáze není dostupná.")).finally(()=>setAuthLoading(false))},[]);
 async function authenticate(e:FormEvent<HTMLFormElement>){e.preventDefault();setAuthLoading(true);setError("");const response=await fetch(bootstrap?"/api/v2/auth/bootstrap":"/api/v2/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});const data=await response.json() as {user?:User;error?:string};if(response.ok&&data.user){setUser(data.user);setBootstrap(false);await loadData(data.user)}else setError(data.error??"Přihlášení se nezdařilo.");setAuthLoading(false)}
 async function logout(){await fetch("/api/v2/auth/logout",{method:"POST"});setUser(null)}
 async function complete(r:Reservation){setBusy(r.id);const response=await fetch(`/api/v2/reservations/${r.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"completed"})});if(response.ok){setReservations(x=>x.map(i=>i.id===r.id?{...i,status:"completed"}:i));setView("completed")}setBusy(null)}
 async function remove(r:Reservation){setBusy(r.id);const response=await fetch(`/api/v2/reservations/${r.id}`,{method:"DELETE"});if(response.ok){setReservations(x=>x.filter(i=>i.id!==r.id));setPendingDelete(null)}setBusy(null)}
 async function savePackage(e:FormEvent<HTMLFormElement>,id?:number){e.preventDefault();const form=e.currentTarget,d=new FormData(form);setBusy(id??"new");const response=await fetch(id?`/api/v2/pricing/${id}`:"/api/v2/pricing",{method:id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:d.get("name"),price:d.get("price"),showCurrency:d.get("showCurrency")==="on",items:String(d.get("items")??"").split("\n")})});if(response.ok){const refreshed=await fetch("/api/v2/pricing");setPackages(((await refreshed.json()) as {packages:Package[]}).packages);if(!id)form.reset();setMessage("Změna ceníku byla provedena.")}setBusy(null)}
 async function saveUser(e:FormEvent<HTMLFormElement>,id?:number){e.preventDefault();const form=e.currentTarget,d=new FormData(form),payload:Record<string,unknown>=Object.fromEntries(d);payload.active=d.get("active")==="on";if(!payload.password)delete payload.password;const response=await fetch(id?`/api/v2/users/${id}`:"/api/v2/users",{method:id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json() as {error?:string};if(response.ok&&user){if(!id)form.reset();await loadData(user);setMessage(id?"Uživatel byl upraven.":"Uživatel byl vytvořen.")}else setError(data.error??"Uložení se nezdařilo.")}
 async function deleteUser(id:number){const response=await fetch(`/api/v2/users/${id}`,{method:"DELETE"});const data=await response.json() as {error?:string};if(response.ok)setUsers(x=>x.filter(i=>i.id!==id));else setError(data.error??"Smazání se nezdařilo.")}
 const active=reservations.filter(r=>r.status==="active"),done=reservations.filter(r=>r.status==="completed"),canEdit=user?.role!=="viewer";
 const table=(rows:Reservation[])=><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Klient</th><th>Telefon</th><th>E-mail</th><th>Služba</th><th>Adresa</th><th>Poznámka</th><th>Akce</th></tr></thead><tbody>{!rows.length&&<tr><td colSpan={7} className={styles.emptyCell}>V tomto seznamu zatím nic není.</td></tr>}{rows.map(r=><tr key={r.id}><td data-label="Klient"><strong>{r.name}</strong></td><td data-label="Telefon"><a href={`tel:${r.phone}`}>{r.phone}</a></td><td data-label="E-mail"><a href={`mailto:${r.email}`}>{r.email}</a></td><td data-label="Služba">{r.service}</td><td data-label="Adresa">{r.address}</td><td data-label="Poznámka">{r.note||"—"}</td><td data-label="Akce"><div className={styles.actions}>{canEdit&&r.status==="active"&&<button className={styles.completeButton} disabled={busy===r.id} onClick={()=>complete(r)}>Hotovo</button>}{canEdit&&<button className={styles.deleteButton} onClick={()=>setPendingDelete(r)}>Smazat</button>}</div></td></tr>)}</tbody></table></div>;
 if(authLoading&&!user)return <main className={styles.page}><p className={styles.state}>Načítám…</p></main>;
 return <main className={styles.page}><Link href="/" className={styles.backLink}>← Zpět na web</Link><section className={user?styles.dashboard:styles.card}><span className={styles.eyebrow}>HOME DETAILING</span>{!user?<><h1>{bootstrap?"První administrátor":"Admin panel"}</h1><p className={styles.intro}>{bootstrap?"Vytvořte první zabezpečený účet.":"Přihlášení pro správce webu."}</p><form className={styles.form} onSubmit={authenticate}>{bootstrap&&<><label>Jméno</label><input name="name" required/><label>Registrační kód</label><input name="code" type="password" required/></>}<label>E-mail</label><input name="email" type="email" required/><label>Heslo</label><input name="password" type="password" minLength={10} required/>{error&&<p className={styles.errorText}>{error}</p>}<button>{bootstrap?"Vytvořit admina":"Přihlásit se"}</button></form></>:<div className={styles.loggedIn}><header className={styles.dashboardHeader}><div><h1>Administrace</h1><p>{user.name} · {user.role}</p></div><button onClick={logout}>Odhlásit se</button></header>{error&&<p className={styles.errorText}>{error}</p>}<div className={styles.lists}><nav className={styles.listTabs}><button className={view==="active"?styles.activeTab:""} onClick={()=>setView("active")}>• Aktivní objednávky <b>{active.length}</b></button><button className={view==="completed"?styles.activeTab:""} onClick={()=>setView("completed")}>• Hotové objednávky <b>{done.length}</b></button><button className={view==="pricing"?styles.activeTab:""} onClick={()=>setView("pricing")}>• Úprava ceníku</button>{user.role==="admin"&&<button className={view==="users"?styles.activeTab:""} onClick={()=>setView("users")}>• Uživatelé</button>}</nav>
 {view==="active"&&<section><h2>Aktivní objednávky</h2>{table(active)}</section>}{view==="completed"&&<section><h2>Hotové objednávky</h2>{table(done)}</section>}
 {view==="pricing"&&<section className={styles.pricingEditor}><h2>Úprava ceníku</h2><div className={styles.packageForms}>{packages.map(p=><form key={p.id} onSubmit={e=>savePackage(e,p.id)}><h3>{p.name}</h3><label>Název<input name="name" defaultValue={p.name} required/></label><label>Cena<input name="price" defaultValue={p.price} required/></label><label className={styles.checkboxLabel}><input name="showCurrency" type="checkbox" defaultChecked={p.showCurrency}/>Zobrazit Kč</label><label>Popisky<textarea name="items" defaultValue={p.items.join("\n")} required/></label><button disabled={!canEdit||busy===p.id}>Uložit změny</button></form>)}{canEdit&&<form className={styles.newPackage} onSubmit={e=>savePackage(e)}><h3>Přidat balíček</h3><label>Název<input name="name" required/></label><label>Cena<input name="price" required/></label><label className={styles.checkboxLabel}><input name="showCurrency" type="checkbox" defaultChecked/>Zobrazit Kč</label><label>Popisky<textarea name="items" required/></label><button>Přidat balíček</button></form>}</div></section>}
 {view==="users"&&user.role==="admin"&&<section className={styles.pricingEditor}><h2>Správa uživatelů</h2><div className={styles.packageForms}>{users.map(u=><form key={u.id} onSubmit={e=>saveUser(e,u.id)}><h3>{u.name}</h3><label>Jméno<input name="name" defaultValue={u.name} required/></label><label>E-mail<input name="email" type="email" defaultValue={u.email} required/></label><label>Role<select name="role" defaultValue={u.role}><option value="admin">Admin</option><option value="manager">Správce</option><option value="viewer">Pouze čtení</option></select></label><label>Nové heslo<input name="password" type="password" minLength={10}/></label><label className={styles.checkboxLabel}><input name="active" type="checkbox" defaultChecked={u.active}/>Aktivní</label><button>Uložit</button>{u.id!==user.id&&<button type="button" className={styles.deleteButton} onClick={()=>deleteUser(u.id)}>Smazat</button>}</form>)}<form className={styles.newPackage} onSubmit={e=>saveUser(e)}><h3>Přidat uživatele</h3><label>Jméno<input name="name" required/></label><label>E-mail<input name="email" type="email" required/></label><label>Heslo<input name="password" type="password" minLength={10} required/></label><label>Role<select name="role"><option value="viewer">Pouze čtení</option><option value="manager">Správce</option><option value="admin">Admin</option></select></label><input name="active" type="hidden" value="on"/><button>Přidat</button></form></div></section>}</div></div>}</section>
 {pendingDelete&&<div className={styles.modalBackdrop}><section className={styles.confirmDialog}><h2>Smazat rezervaci?</h2><p>Rezervace klienta <strong>{pendingDelete.name}</strong> bude trvale odstraněna.</p><div className={styles.dialogActions}><button className={styles.cancelButton} onClick={()=>setPendingDelete(null)}>Vrátit</button><button className={styles.confirmDeleteButton} onClick={()=>remove(pendingDelete)}>Smazat</button></div></section></div>}{message&&<div className={styles.modalBackdrop}><section className={styles.confirmDialog}><h2>{message}</h2><button className={styles.confirmDeleteButton} onClick={()=>setMessage("")}>OK</button></section></div>}</main>
}
