#!/usr/bin/env node
// Computes the next version, prepends a section to CHANGELOG.md and writes the
// version into package.json. Git commit/tag/push and the GitHub Release are
// done by the workflow (.github/workflows/ci.yml, job `release`).
//
//   node scripts/release.mjs [--dry-run] [--notes <file>]
//   RELEASE_BUMP=patch|minor|major   (default patch; the workflow derives it from PR labels)
//
// First release (no v* tag yet): the version in package.json is released as is.
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const notesIndex = args.indexOf("--notes");
const notesFile = notesIndex >= 0 ? args[notesIndex + 1] : null;
const bump = process.env.RELEASE_BUMP || "patch";
if (!["patch", "minor", "major"].includes(bump)) {
  console.error(`Unknown RELEASE_BUMP "${bump}" (expected patch, minor or major)`);
  process.exit(1);
}

const git = (...argv) => execFileSync("git", argv, { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();

const pkgPath = resolve(root, "package.json");
const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));

let lastTag = null;
try {
  lastTag = git("describe", "--tags", "--abbrev=0", "--match", "v*");
} catch {
  lastTag = null;
}

function nextVersion() {
  if (!lastTag) return pkg.version;
  const [major, minor, patch] = lastTag.slice(1).split(".").map(Number);
  if (bump === "major") return `${major + 1}.0.0`;
  if (bump === "minor") return `${major}.${minor + 1}.0`;
  return `${major}.${minor}.${patch + 1}`;
}

const version = nextVersion();
const range = lastTag ? `${lastTag}..HEAD` : "HEAD";
const commits = git("log", "--no-merges", "--pretty=- %s (%h)", range)
  .split("\n")
  .filter((line) => line && !/^- chore\(release\):/.test(line));
const date = new Date().toISOString().slice(0, 10);
const section = `## v${version} · ${date}\n\n${commits.length ? commits.join("\n") : "- No changes"}\n`;

const changelogPath = resolve(root, "CHANGELOG.md");
const existing = existsSync(changelogPath) ? readFileSync(changelogPath, "utf8") : "";
const header = "# Changelog\n\nGenerated by CI on every merge to `main` (`scripts/release.mjs`). Do not edit by hand.\n\n";
const body = existing.startsWith("# Changelog") ? existing.slice(existing.indexOf("\n## ") + 1) : "";
const changelog = header + section + (body ? `\n${body}` : "");

console.log(`last tag: ${lastTag ?? "(none, first release)"}`);
console.log(`bump: ${lastTag ? bump : "none"} → v${version}`);
console.log(`commits: ${commits.length}`);
console.log(`\n${section}`);

if (!dryRun) {
  pkg.version = version;
  writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
  writeFileSync(changelogPath, changelog);
  if (notesFile) writeFileSync(resolve(notesFile), section);
  if (process.env.GITHUB_OUTPUT) writeFileSync(process.env.GITHUB_OUTPUT, `version=${version}\ntag=v${version}\n`, { flag: "a" });
}
